### ISSUE TITLE
搜索到了文件 但是回车后  就是打开了https://192.168.2.100/file/ 网页不是对应的文件目录

### ISSUE THREAD

**Issue by zhiyicai** [VaalaCat/synology-alfred#2]
搜索到了文件 但是回车后  就是打开了https://192.168.2.100/file/ 网页不是对应的文件目录
版本： alfred 5 
同时也 无法搜索数字

**Comment by VaalaCat** [comment]
预期内，因为dsm的file路径数据提交在POST body中，没有找到比较好的从alfred redirect 到dsm指定路径的方法
