### ISSUE TITLE
How do you install this?

### ISSUE THREAD

**Issue by punkhop** [VaalaCat/synology-alfred#3]
I've got Alfred and a Synology that I'd love to introduce to each other. I've installed the workflow in Alfred, but how do I set it to index my Synology?

**Comment by VaalaCat** [comment]
Actually I've wrote a blog for this, [Synology Alfred](https://vaala.cat/2022/01/29/%E5%9C%A8Alfred%E4%B8%AD%E4%B8%9D%E6%BB%91%E7%9A%84%E6%90%9C%E7%B4%A2%E7%BE%A4%E6%99%96NAS%E4%B8%AD%E7%9A%84%E6%96%87%E4%BB%B6/)。

And the install guide is simple, just download the file from release, and follow the instruction from alfred, if you need an readme file. I can tell you that I'm working on it 😉.

**Comment by VaalaCat** [comment]
finish add the install instructions in readme, close issue
